### ISSUE TITLE
jncryptor.InvalidHMACException: Incorrect HMAC value.

### ISSUE THREAD

**Issue by maplesnow-zsm** [RNCryptor/JNCryptor#30] opened 2015-11-02 09:25 UTC
this is the problem about "jncryptor.InvalidHMACException" in android, when i use gson and Base64.decode before the decrypt:

Gson gson = new Gson();
AES256JNCryptor aes256JNCryptor = new AES256JNCryptor();
String string = gson.toJson(data);
byte[] bytes = Base64.decode(string, 0);

then it throw the exception:

com.ilikelabsapp.MeiFu.frame.utils.jncryptor.InvalidHMACException: Incorrect HMAC value.
com.ilikelabsapp.MeiFu.frame.utils.jncryptor.AES256JNCryptor.decryptV3Data(AES256JNCryptor.java:248)
com.ilikelabsapp.MeiFu.frame.utils.jncryptor.AES256JNCryptor.decryptData(AES256JNCryptor.java:280)
com.ilikelabsapp.MeiFu.frame.entity.EncryptNetworkResponse.getData(EncryptNetworkResponse.java:55)

if only i don't use the base64.decode, then it will throw the exception:

jncryptor.CryptorException: Unrecognised version number: 34.
com.ilikelabsapp.MeiFu.frame.utils.jncryptor.AES256JNCryptor.decryptData(AES256JNCryptor.java:283)
com.ilikelabsapp.MeiFu.frame.entity.EncryptNetworkResponse.getData(EncryptNetworkResponse.java:56)

i don't kow how to slove the InvalidHMACException, did i do anything wrong?
Thank you~

**Comment by rnapier** [comment] 2015-11-02 11:59
Invalid hmac means either your data is corrupted or you have the wrong password. The input must be precisely (byte for byte) the output of the encryptor.

**Comment by maplesnow-zsm** [comment] 2015-11-03 07:30
yes, i find the reason,it's caused by gson, it filtered the escape character like " / " and " ' " and so on,so the data is corrupted,i use "Gson gson = new GsonBuilder().setPrettyPrinting().disableHtmlEscaping().create();" to solve the issue.

Thank you for the support,there is still another problem,it's too slow in android, it takes me about 3.2s to decrypt,so i'm afraid of i can't use it, hope it can be solved soon~

Thanks again for the cool code~

**Comment by dmjones500** [comment] 2016-05-25 10:24
Main issue is solved. Performance problem is duplicate of #23

**Closed by dmjones500** 2016-05-25 10:24 UTC
