### ISSUE TITLE
decode problem on android

### ISSUE THREAD

**Issue by aliab** [RNCryptor/JNCryptor#21] opened 2014-08-28 22:27 UTC
i want to decode, an encrypted image on android, but what i get, is a corrupted file! am i doing it in a wrong way?!
here is my code base on sample code you made:

``` java
final String password = "my_password";

JNCryptor cryptor = new AES256JNCryptor();
Resources res = getResources();
InputStream in_s = res.openRawResource(R.raw.troodon_ph);
byte[] b = null;
byte[] data = null;
try {
  b = new byte[in_s.available()];
  in_s.read(b);
} catch (IOException e) {
  Log.i("decrypt error", e.toString());
}



AES256JNCryptorOutputStream cryptorStream = null;

ByteArrayOutputStream byteStream = new ByteArrayOutputStream();
try {
  cryptorStream = new AES256JNCryptorOutputStream(byteStream,
      password.toCharArray());

} catch (CryptorException e) {
  e.printStackTrace();
}

try {
  cryptorStream.write(b);
  cryptorStream.flush();
  cryptorStream.close();
} catch (IOException e1) {
  e1.printStackTrace();
}

byte[] encrypted = byteStream.toByteArray();

try {
  data = cryptor.decryptData(encrypted, password.toCharArray());
} catch (InvalidHMACException e) {
  e.printStackTrace();
} catch (CryptorException e) {
  e.printStackTrace();
}

if (data != null) {
  Toast.makeText(getApplicationContext(), "data is ok",
      Toast.LENGTH_SHORT).show();

  Bitmap mBitmap = BitmapFactory
      .decodeByteArray(data, 0, data.length);

  new SavePhotoTask().execute(data);

                    ///////// here is a problem! mBitmap is always null.
  if(mBitmap == null){
    Toast.makeText(getApplicationContext(), "bitmap is null!",
        Toast.LENGTH_SHORT).show();
  }

  BitmapDrawable bDrawable = new BitmapDrawable(res, mBitmap);
  img.setBackgroundDrawable(bDrawable);
} else {
  Toast.makeText(getApplicationContext(), "data is null",
      Toast.LENGTH_SHORT).show();
}
```

**Comment by dmjones500** [comment] 2017-04-05 17:40
I'm going to close the issue due to its age and the fact that the last comment suggests the problem isn't relevant any more. Please open a new issue if needed.

**Closed by dmjones500** 2017-04-05 17:40 UTC

**Comment by alokomkar** [comment] 2018-01-23 09:58
```
//Encrypt file
/**
 *
var encryptedData = RNCryptor.encrypt(data: data as Data, withPassword: hashKey.description)
try encryptedData.write(to: fileURL)
 * */
fun encryptFile( inputFile : File ) : File {

    val size = inputFile.length().toInt()
    val fileBytes = ByteArray(size)
    val aeS256JNCryptor = AES256JNCryptor()
    val file = File(Environment.getExternalStorageDirectory().toString() + "/Encrypted_" + inputFile.name)
    try {
        val buf = BufferedInputStream(FileInputStream(inputFile))
        buf.read(fileBytes, 0, fileBytes.size)

        val encryptedFileBytes = aeS256JNCryptor.encryptData(fileBytes, "master".toCharArray())

        val bufOut = BufferedOutputStream(FileOutputStream(file))
        bufOut.write(encryptedFileBytes)

        buf.close()
        bufOut.close()

    } catch (e: FileNotFoundException) {
        // TODO Auto-generated catch block
        e.printStackTrace()
    } catch (e: IOException) {
        // TODO Auto-generated catch block
        e.printStackTrace()
    }

    return file

}

//Decrypt file
/**
 *
let encryptedData = fileManager.contents(atPath: filePathNormal)
let decryptedData = try RNCryptor.decrypt(data: encryptedData!, withPassword: hashKey.description)
let selected_image = UIImage.sd_image(with: decryptedData)
 * */
fun decryptFile( inputFile : File ) : File {

    val size = inputFile.length().toInt()
    val fileBytes = ByteArray(size)
    val aeS256JNCryptor = AES256JNCryptor()
    val file = File(Environment.getExternalStorageDirectory().toString() + "/Decrypted_" + inputFile.name)
    try {
        val buf = BufferedInputStream(FileInputStream(inputFile))
        buf.read(fileBytes, 0, fileBytes.size)

        val decryptedFileBytes = aeS256JNCryptor.decryptData(fileBytes, "master".toCharArray())

        val bufOut = BufferedOutputStream(file.outputStream())
        bufOut.write(decryptedFileBytes)

        buf.close()
        bufOut.close()

    } catch (e: FileNotFoundException) {
        // TODO Auto-generated catch block
        e.printStackTrace()
    } catch (e: IOException) {
        // TODO Auto-generated catch block
        e.printStackTrace()
    }

    return file
}
```

I am using the above code to encrypt / decrypt file using JNCryptor. I am using a image file for encryption, however post decryption I am unable to load / view the image either from gallery or in app. 

Any help is appreciated. Let me know if I am going wrong somewhere.
