### ISSUE TITLE
JNCryptor on android is too slow than RNEncryptor on iOS

### ISSUE THREAD

**Issue by cs8** [RNCryptor/JNCryptor#34] opened 2016-04-13 02:32 UTC
do you know how to make it fast on android ?

**Comment by LookingSharp** [comment] 2016-05-12 21:17
I've read through some of the issues, and I'm wondering if anyone has profiled what is slow.  There were some hints that this was because of the pbkdf2, which is of course _designed_ to be slow.

I'm wondering if you use an encryption key directly (and don't derive it from the password every time) are there still performance problems?

**Comment by TGIO** [comment] 2016-05-19 19:33
perfomance issues solved in [this](https://github.com/TGIO/RNCryptorNative) implementation

**Comment by dmjones500** [comment] 2016-05-25 10:21
Duplicate of #23

**Closed** 2016-05-25 10:20 UTC
